# -*- coding: utf-8 -*-
"""NewStrategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ftpYT62I_6oykSYsOnj2L8Ns63BsZE4
"""

import random

def bot_strategy(card: int, bot_hand: list[int], opponent_moves: list[int]) -> int:
    if not bot_hand:
        return None

    if card < 7:
        options = [c for c in bot_hand if c < card or (card < c <= card + 2)]

    elif card == 7:
        options = [c for c in bot_hand if c in [8, 9] or c < 7]

    elif card == 8:
        options = [c for c in bot_hand if c in [9, 10, 11]]

    elif card == 9:
        options = [c for c in bot_hand if c in [10, 11]]

    elif card == 10:
        options = [c for c in bot_hand if c in [10, 11, 12]]

    elif card == 11:
        options = [c for c in bot_hand if c in [11, 12, 13]]

    elif card == 13:
        if 13 in opponent_moves:
            if 13 in bot_hand:
                return 13
            else:
                options = bot_hand
        else:
            options = [c for c in bot_hand if c != 13]
            if not options:
                options = bot_hand

    else:
        options = bot_hand

    if not options:
        return random.choice(bot_hand)

    choice = max(options)
    bot_hand.remove(choice)
    return choice