# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ftpYT62I_6oykSYsOnj2L8Ns63BsZE4
"""

def calculate_scores(bot_hands: dict) -> dict:
    values = {
        "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7,
        "8": 8, "9": 9, "10": 10,
        "J": 11, "Q": 12, "K": 13, "A": 14
    }

    scores = {}

    for bot, cards in bot_hands.items():
        score = 0
        for card in cards:
            rank = card[:-1]
            score += values.get(rank, 0)
        scores[bot] = score

    return scores